# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          KwonYool
baseurl:        ""
url:            "http://benesiaxd.githun.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Kwon Yool
  url:          https://benesiaxd.github.io
  email:        benesiaxd@gmail.com
  github:       benesiaxd
  kakao:      jasperxd

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/benesiaxd/benesiaxd.github.io
